name: Publish docs via GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: mkdocs build --strict
      run: |
        docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build --config-file docs/mkdocs.yml --strict
  deploy:
    name: Deploy documentation to gh-pages
    runs-on: ubuntu-20.04
    if: github.event_name = 'push'
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: mkdocs build --strict
      run: |
        docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build --config-file docs/mkdocs.yml --strict
    - name: Publish documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/site
        user_name: 'github-actions[bot]'
        user_email: '41898282+github-actions[bot]@users.noreply.github.com'
