name: Publish docs via GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: mkdocs build --strict
      run: |
        docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material build --config-file docs/mkdocs.yml --strict
  deploy:
    name: Deploy documentation to gh-pages
    runs-on: ubuntu-20.04
    if: github.event_name != 'pull_request'
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: mkdocs gh-pages --force
      run: |
        docker run --rm -v ${PWD}:/docs squidfunk/mkdocs-material gh-deploy  --config-file docs/mkdocs.yml --force
